<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDo3nrt9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDo3nrt9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDo3nrt9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDo3nrt9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDo3nrt9\appProdProjectContainer([
    'container.build_hash' => 'Do3nrt9',
    'container.build_id' => 'f5073d74',
    'container.build_time' => 1613573013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDo3nrt9');
